### ISSUE TITLE
Global variable usage clarification 

### ISSUE THREAD

**Issue by SubhadeepJasu** [yumiris/SPV3#1]
Since f1 is for pp, shouldn't f3 be used for levels (and locking being an after thought)?

**Comment by MirisWisdom** [comment]
That's correct -- the excuse for stating that F3 is for locking is to passive aggressively express my disdain for locking mechanisms.

**Comment by SubhadeepJasu** [comment]
Never thought I'll write this in an issue but

LMAO!!!
